name: Run Maestro against React Native
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.12
          
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.5"
          cache: pnpm
          
      - name: pnpm install
        run: pnpm install
